### ISSUE TITLE
videojs panorama not woking correctly with videojs-contrib-hls on firefox

### ISSUE THREAD

**Issue by mostafa-v** [yanwsh/videojs-panorama#27] opened 2016-10-26 20:59 UTC
Hi
I Use videojs panorama with videojs-contrib-hls. It works fine in chrome, but in firefox, the video is totally black but sound works.
So to put it all together, 
Videojs panorama with a mp4 file as source works fine in both chrome and firefox
Our hls streams works fine in videojs with videojs-contrib-hls in both chrome and firefox
But combination of these plugins works fine in chrome but not firefox.

I asked this question in another issue and you said you will test it, but i didn't get an answer.
Our project is under development, but I can provide links to your email if needed.

**Comment by yanwsh** [comment] 2016-11-08 02:21
I didn't use videojs-contrib-hls plugin before, could you email me your code snippet if you can. yanwsh@gmail.com

Thank you

**Comment by smallSquirrel** [comment] 2016-11-14 03:49
@mostafa-v  Hello my friends; videojs-contrib-hls plug-in and video-panorama playback VR panoramic video (m3u8 format) you solve it?

**Comment by smallSquirrel** [comment] 2016-11-14 03:51
@yanwsh Hello, I have a question to consult you, video-panorama can support hls video(m3u8) player?

**Comment by yanwsh** [comment] 2016-11-14 04:00
i think yes, it  supports. But have some issues. Could you send me video? I don't have video to test it. Thank you.

**Comment by mostafa-v** [comment] 2016-11-14 05:43
@yanwsh I have sent the videos to you, I did it with my mobile and I hope I send you correct links. I will go to my pc in an hour and recheck the links. Thanks

**Comment by yanwsh** [comment] 2016-11-15 18:15
please update the latest version of this plugin, the black screen issue should be fixed now. Checking both on firefox and safari.

**Comment by mostafa-v** [comment] 2016-11-16 12:58
@yanwsh The problem has been solved! Thanks a lot.

**Closed** 2016-12-13 09:58 UTC

**Comment by jeremy-st** [comment] 2016-12-14 23:54
I am having the same issue but it is all browsers desktop as well as iphone 7 with iOS 10.

**Comment by jeremy-st** [comment] 2016-12-15 00:48
On the desktop if i let the whole video play without video but with sound all the way through and then hit play again the video works. I can not get anything to work on the iPhone. BTW, My video is being hosted with Wowza.

**Comment by deltafactory** [comment] 2017-05-05 14:05
This may be related, but when using panorama + HLS with autoplay, I do not see the video until I interact with the player controls. I believe the demo uses the `callback: function(){ player.play(); }` which emulates autoplay, somehow avoiding this bug.

I wonder if the issue is related to z-index positioning of the panorama canvas vs the usual 2d playback canvas?

**Comment by deltafactory** [comment] 2017-05-05 14:15
Possibly a quick answer:

I see here an event handler for `player.on("play")` that calls `canvas.show()`.
https://github.com/yanwsh/videojs-panorama/blob/master/src/scripts/plugin.js#L157

Does there need to be an additional check in case the video is already playing?
